"""add_calculated_sum_fields_to_budget_category

Revision ID: fe3d159bb700
Revises: 48ac351fabda
Create Date: 2025-05-07 23:28:05.444413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3d159bb700'
down_revision: Union[str, None] = '48ac351fabda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('total_expense', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('budgets', sa.Column('total_income', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('budgets', sa.Column('balance', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('categories', sa.Column('spent', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('categories', sa.Column('income', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('categories', sa.Column('balance', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'balance')
    op.drop_column('categories', 'income')
    op.drop_column('categories', 'spent')
    op.drop_column('budgets', 'balance')
    op.drop_column('budgets', 'total_income')
    op.drop_column('budgets', 'total_expense')
    # ### end Alembic commands ###
